title: Shoko Anime
description: Your Archive, Your Way.
#url: https://shokoanime.com/newsite
url: http://localhost:3000
permalink:   /blog/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
plugins:
- jekyll-sitemap
- jekyll-paginate-v2

exclude: ['README.markdown', 'Gemfile.lock', 'Gemfile', "README.md", "CNAME", "templates", "package.json", "package-lock.json", "node_modules", "gulpfile.js", "_site", "yarn.lock"]

pagination:
  enabled: true
  debug: true
  collection: 'posts'
  per_page: 8
  permalink: '/page/:num/'
  title: ':title - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  category: 'posts'
  trail:
    before: 2
    after: 2