baseURL = "https://shokoanime.com/"
#baseURL = "https://shokoanime.com/devsite/"
DefaultContentLanguage = "en"
paginate =  6
title = "Shoko"

disableKinds = ["taxonomyTerm"]

[outputs]
	home = ["HTML", "RSS", "JSON"]

[permalinks]
	category = "/blog/category/:slug/"
	tag = "/blog/tag/:slug/"

[taxonomies]
	category = "category"
	tag = "tag"

[markup.goldmark.renderer]
	unsafe= true

[languages]
	[languages.en]
		contentDir = "content/en"
		title = "Shoko"
		languageName = "English"
		weight = 1
	[languages.de]
		contentDir = "content/de"
		title = "Shoko"
		languageName = "Deutsch"
		weight = 2

[params]
  images = ["icon.png"]